apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: html-gitlab-aaaaa-f2194547-d9ea-4792-b0d9-28e5a1e1dccf
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/html-gitlab-aaaaa-f2194547-d9ea-4792-b0d9-28e5a1e1dccf.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: html-gitlab-aaaaa-f2194547-d9ea-4792-b0d9-28e5a1e1dccf
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
